/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/Food": {
    get: {
      parameters: {
        query: {
          created_at?: parameters["rowFilter.Food.created_at"];
          name?: parameters["rowFilter.Food.name"];
          fat?: parameters["rowFilter.Food.fat"];
          carbohydrates?: parameters["rowFilter.Food.carbohydrates"];
          protein?: parameters["rowFilter.Food.protein"];
          bar_code?: parameters["rowFilter.Food.bar_code"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["Food"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** Food */
          Food?: definitions["Food"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          created_at?: parameters["rowFilter.Food.created_at"];
          name?: parameters["rowFilter.Food.name"];
          fat?: parameters["rowFilter.Food.fat"];
          carbohydrates?: parameters["rowFilter.Food.carbohydrates"];
          protein?: parameters["rowFilter.Food.protein"];
          bar_code?: parameters["rowFilter.Food.bar_code"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          created_at?: parameters["rowFilter.Food.created_at"];
          name?: parameters["rowFilter.Food.name"];
          fat?: parameters["rowFilter.Food.fat"];
          carbohydrates?: parameters["rowFilter.Food.carbohydrates"];
          protein?: parameters["rowFilter.Food.protein"];
          bar_code?: parameters["rowFilter.Food.bar_code"];
        };
        body: {
          /** Food */
          Food?: definitions["Food"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  /** @description Food and their nutritional values */
  Food: {
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: character varying */
    name?: string;
    /** Format: smallint */
    fat?: number;
    /** Format: smallint */
    carbohydrates?: number;
    /** Format: smallint */
    protein?: number;
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    bar_code: number;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description Food */
  "body.Food": definitions["Food"];
  /** Format: timestamp with time zone */
  "rowFilter.Food.created_at": string;
  /** Format: character varying */
  "rowFilter.Food.name": string;
  /** Format: smallint */
  "rowFilter.Food.fat": string;
  /** Format: smallint */
  "rowFilter.Food.carbohydrates": string;
  /** Format: smallint */
  "rowFilter.Food.protein": string;
  /** Format: bigint */
  "rowFilter.Food.bar_code": string;
}

export interface operations {}

export interface external {}
